package net.veroxuniverse.crystal_chronicles.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.veroxuniverse.crystal_chronicles.CrystalChronicles;
import net.veroxuniverse.crystal_chronicles.fluid.CCFluids;

public class CCTabs {

    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, CrystalChronicles.MODID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CC_TAB_BLOCKS = CREATIVE_MODE_TABS.register("cc_tab_blocks", () -> CreativeModeTab.builder()
            .title(Component.translatable("itemGroup.blocks." + CrystalChronicles.MODID))
            .icon(() -> CCBlocks.RAINBOW_BISMUTH_BRICKS.get().asItem().getDefaultInstance())
            .displayItems((parameters, output) -> {
                output.accept(CCBlocks.POLISHED_STONE_BRICKS.get());
                output.accept(CCBlocks.PORTAL_FRAME_BLOCK.get());
                output.accept(CCBlocks.BISMITE.get());
                output.accept(CCBlocks.BISMITE_STAIRS.get());
                output.accept(CCBlocks.BISMITE_SLAB.get());
                output.accept(CCBlocks.BISMITE_WALL.get());
                output.accept(CCBlocks.BISMITE_BRICKS.get());
                output.accept(CCBlocks.BISMITE_BRICKS_STAIRS.get());
                output.accept(CCBlocks.BISMITE_BRICKS_SLAB.get());
                output.accept(CCBlocks.BISMITE_BRICKS_WALL.get());
                output.accept(CCBlocks.CHISELED_BISMITE.get());
                output.accept(CCBlocks.CHISELED_BISMITE_STAIRS.get());
                output.accept(CCBlocks.CHISELED_BISMITE_SLAB.get());
                output.accept(CCBlocks.CHISELED_BISMITE_WALL.get());
                output.accept(CCBlocks.CRACKED_BISMITE.get());
                output.accept(CCBlocks.CRACKED_BISMITE_STAIRS.get());
                output.accept(CCBlocks.CRACKED_BISMITE_SLAB.get());
                output.accept(CCBlocks.CRACKED_BISMITE_WALL.get());
                output.accept(CCBlocks.POLISHED_BISMITE.get());
                output.accept(CCBlocks.POLISHED_BISMITE_STAIRS.get());
                output.accept(CCBlocks.POLISHED_BISMITE_SLAB.get());
                output.accept(CCBlocks.POLISHED_BISMITE_WALL.get());
                output.accept(CCBlocks.BLUE_BISMUTH_BRICKS.get());
                output.accept(CCBlocks.BLUE_BISMUTH_BRICKS_STAIRS.get());
                output.accept(CCBlocks.BLUE_BISMUTH_BRICKS_SLAB.get());
                output.accept(CCBlocks.BLUE_BISMUTH_BRICKS_WALL.get());
                output.accept(CCBlocks.PURPLE_BISMUTH_BRICKS.get());
                output.accept(CCBlocks.PURPLE_BISMUTH_BRICKS_STAIRS.get());
                output.accept(CCBlocks.PURPLE_BISMUTH_BRICKS_SLAB.get());
                output.accept(CCBlocks.PURPLE_BISMUTH_BRICKS_WALL.get());
                output.accept(CCBlocks.RAINBOW_BISMUTH_BRICKS.get());
                output.accept(CCBlocks.RAINBOW_BISMUTH_BRICKS_STAIRS.get());
                output.accept(CCBlocks.RAINBOW_BISMUTH_BRICKS_SLAB.get());
                output.accept(CCBlocks.RAINBOW_BISMUTH_BRICKS_WALL.get());
                output.accept(CCBlocks.VIOLET_BISMUTH_BRICKS.get());
                output.accept(CCBlocks.VIOLET_BISMUTH_BRICKS_STAIRS.get());
                output.accept(CCBlocks.VIOLET_BISMUTH_BRICKS_SLAB.get());
                output.accept(CCBlocks.VIOLET_BISMUTH_BRICKS_WALL.get());
                output.accept(CCBlocks.YELLOW_BISMUTH_BRICKS.get());
                output.accept(CCBlocks.YELLOW_BISMUTH_BRICKS_STAIRS.get());
                output.accept(CCBlocks.YELLOW_BISMUTH_BRICKS_SLAB.get());
                output.accept(CCBlocks.YELLOW_BISMUTH_BRICKS_WALL.get());
                output.accept(CCBlocks.BLUE_BISMUTH.get());
                output.accept(CCBlocks.BLUE_BISMUTH_STAIRS.get());
                output.accept(CCBlocks.BLUE_BISMUTH_SLAB.get());
                output.accept(CCBlocks.BLUE_BISMUTH_WALL.get());
                output.accept(CCBlocks.PURPLE_BISMUTH.get());
                output.accept(CCBlocks.PURPLE_BISMUTH_STAIRS.get());
                output.accept(CCBlocks.PURPLE_BISMUTH_SLAB.get());
                output.accept(CCBlocks.PURPLE_BISMUTH_WALL.get());
                output.accept(CCBlocks.VIOLET_BISMUTH.get());
                output.accept(CCBlocks.VIOLET_BISMUTH_STAIRS.get());
                output.accept(CCBlocks.VIOLET_BISMUTH_SLAB.get());
                output.accept(CCBlocks.VIOLET_BISMUTH_WALL.get());
                output.accept(CCBlocks.YELLOW_BISMUTH.get());
                output.accept(CCBlocks.YELLOW_BISMUTH_STAIRS.get());
                output.accept(CCBlocks.YELLOW_BISMUTH_SLAB.get());
                output.accept(CCBlocks.YELLOW_BISMUTH_WALL.get());
                output.accept(CCBlocks.BLUE_BISMUTH_CRYSTAL.get());
                output.accept(CCBlocks.PURPLE_BISMUTH_CRYSTAL.get());
                output.accept(CCBlocks.RAINBOW_BISMUTH_CRYSTAL.get());
                output.accept(CCBlocks.VIOLET_BISMUTH_CRYSTAL.get());
                output.accept(CCBlocks.YELLOW_BISMUTH_CRYSTAL.get());
                output.accept(CCBlocks.VILLI.get());
                output.accept(CCBlocks.TALL_VILLI.get());
                output.accept(CCBlocks.VEINS.get());
                output.accept(CCBlocks.FLESH_BLOCK.get());
                output.accept(CCBlocks.MUSCLE_BLOCK.get());
                output.accept(CCBlocks.TENDON_BLOCK.get());
                output.accept(CCBlocks.ALVEOLUS_BLOCK.get());
                output.accept(CCBlocks.FAT_TISSUE_BLOCK.get());
                output.accept(CCBlocks.ARTREE_BASE.get());
                output.accept(CCBlocks.ARTREE_VEIN.get());
                output.accept(CCBlocks.ARTREE_CAPILLARY.get());
                output.accept(CCBlocks.NEURON_BLOCK.get());
                output.accept(CCBlocks.AXON.get());
                output.accept(CCItems.NEURON_TORCH_ITEM.get());
                output.accept(CCBlocks.ALVEOLUS.get());
                output.accept(CCBlocks.BRONCHUS.get());
                output.accept(CCBlocks.BRONCHUS_PLANKS.get());
                output.accept(CCBlocks.BRONCHUS_STAIRS.get());
                output.accept(CCBlocks.BRONCHUS_SLAB.get());
                output.accept(CCBlocks.BRONCHUS_FENCE.get());
                output.accept(CCBlocks.BRONCHUS_FENCE_GATE.get());
                output.accept(CCBlocks.BRONCHUS_BUTTON.get());
                output.accept(CCBlocks.BRONCHUS_PRESSURE_PLATE.get());
                output.accept(CCBlocks.BRONCHUS_DOOR.get());
                output.accept(CCBlocks.BRONCHUS_TRAPDOOR.get());
                output.accept(CCBlocks.CRUSTONE.get());
                output.accept(CCBlocks.CRUSTONE_STAIRS.get());
                output.accept(CCBlocks.CRUSTONE_SLAB.get());
                output.accept(CCBlocks.CRUSTONE_WALL.get());
                output.accept(CCBlocks.CRUSTONE_BRICKS.get());
                output.accept(CCBlocks.CRUSTONE_BRICKS_STAIRS.get());
                output.accept(CCBlocks.CRUSTONE_BRICKS_SLAB.get());
                output.accept(CCBlocks.CRUSTONE_BRICKS_WALL.get());
                output.accept(CCBlocks.CRACKED_CRUSTONE_BRICKS.get());
                output.accept(CCBlocks.CRACKED_CRUSTONE_BRICKS_STAIRS.get());
                output.accept(CCBlocks.CRACKED_CRUSTONE_BRICKS_SLAB.get());
                output.accept(CCBlocks.CRACKED_CRUSTONE_BRICKS_WALL.get());
                output.accept(CCBlocks.POLISHED_CRUSTONE.get());
                output.accept(CCBlocks.POLISHED_CRUSTONE_STAIRS.get());
                output.accept(CCBlocks.POLISHED_CRUSTONE_SLAB.get());
                output.accept(CCBlocks.POLISHED_CRUSTONE_WALL.get());
                output.accept(CCBlocks.CHISELED_CRUSTONE.get());
                output.accept(CCBlocks.CHISELED_CRUSTONE_STAIRS.get());
                output.accept(CCBlocks.CHISELED_CRUSTONE_SLAB.get());
                output.accept(CCBlocks.CHISELED_CRUSTONE_WALL.get());
                output.accept(CCBlocks.EYE_BLOCK.get());
                output.accept(CCBlocks.HANGING_VEINS.get());
                output.accept(CCBlocks.CELVER_LIGHT.get());
                output.accept(CCBlocks.SKIN_LAYER.get());
                output.accept(CCBlocks.ROTTEN_FLESH_BLOCK.get());
                output.accept(CCBlocks.HEMALITE_BLOCK.get());
                output.accept(CCBlocks.CLOUD_BLOCK.get());
                output.accept(CCBlocks.CLOUD_LAYER.get());
                output.accept(CCBlocks.DENSE_CLOUDS.get());
                output.accept(CCBlocks.HOLY_MARBLE.get());
                output.accept(CCBlocks.HOLY_MARBLE_STAIRS.get());
                output.accept(CCBlocks.HOLY_MARBLE_SLAB.get());
                output.accept(CCBlocks.HOLY_MARBLE_WALL.get());
                output.accept(CCBlocks.HOLY_MARBLE_BRICKS.get());
                output.accept(CCBlocks.HOLY_MARBLE_BRICKS_STAIRS.get());
                output.accept(CCBlocks.HOLY_MARBLE_BRICKS_SLAB.get());
                output.accept(CCBlocks.HOLY_MARBLE_BRICKS_WALL.get());
                output.accept(CCBlocks.CHISELED_HOLY_MARBLE.get());
                output.accept(CCBlocks.CHISELED_HOLY_MARBLE_STAIRS.get());
                output.accept(CCBlocks.CHISELED_HOLY_MARBLE_SLAB.get());
                output.accept(CCBlocks.CHISELED_HOLY_MARBLE_WALL.get());
                output.accept(CCBlocks.CRACKED_HOLY_MARBLE.get());
                output.accept(CCBlocks.CRACKED_HOLY_MARBLE_STAIRS.get());
                output.accept(CCBlocks.CRACKED_HOLY_MARBLE_SLAB.get());
                output.accept(CCBlocks.CRACKED_HOLY_MARBLE_WALL.get());
                output.accept(CCBlocks.POLISHED_HOLY_MARBLE.get());
                output.accept(CCBlocks.POLISHED_HOLY_MARBLE_STAIRS.get());
                output.accept(CCBlocks.POLISHED_HOLY_MARBLE_SLAB.get());
                output.accept(CCBlocks.POLISHED_HOLY_MARBLE_WALL.get());
                output.accept(CCBlocks.HOLY_MARBLE_PILLAR.get());
                output.accept(CCBlocks.GOLDSTONE.get());
                output.accept(CCBlocks.GOLDSTONE_STAIRS.get());
                output.accept(CCBlocks.GOLDSTONE_SLAB.get());
                output.accept(CCBlocks.GOLDSTONE_WALL.get());
                output.accept(CCBlocks.HOLY_LIGHT_BLOCK.get());
                output.accept(CCBlocks.HOLY_BEACON.get());
                output.accept(CCBlocks.PUMICE.get());
                output.accept(CCBlocks.PUMICE_STAIRS.get());
                output.accept(CCBlocks.PUMICE_SLAB.get());
                output.accept(CCBlocks.PUMICE_WALL.get());
                output.accept(CCBlocks.PUMICE_BRICKS.get());
                output.accept(CCBlocks.PUMICE_BRICKS_STAIRS.get());
                output.accept(CCBlocks.PUMICE_BRICKS_SLAB.get());
                output.accept(CCBlocks.PUMICE_BRICKS_WALL.get());
                output.accept(CCBlocks.CHISELED_PUMICE.get());
                output.accept(CCBlocks.CHISELED_PUMICE_STAIRS.get());
                output.accept(CCBlocks.CHISELED_PUMICE_SLAB.get());
                output.accept(CCBlocks.CHISELED_PUMICE_WALL.get());
                output.accept(CCBlocks.CRACKED_PUMICE.get());
                output.accept(CCBlocks.CRACKED_PUMICE_STAIRS.get());
                output.accept(CCBlocks.CRACKED_PUMICE_SLAB.get());
                output.accept(CCBlocks.CRACKED_PUMICE_WALL.get());
                output.accept(CCBlocks.POLISHED_PUMICE.get());
                output.accept(CCBlocks.POLISHED_PUMICE_STAIRS.get());
                output.accept(CCBlocks.POLISHED_PUMICE_SLAB.get());
                output.accept(CCBlocks.POLISHED_PUMICE_WALL.get());
                output.accept(CCBlocks.PYRITE.get());
                output.accept(CCBlocks.PYRITE_STAIRS.get());
                output.accept(CCBlocks.PYRITE_SLAB.get());
                output.accept(CCBlocks.PYRITE_WALL.get());
                output.accept(CCBlocks.PYRITE_CHUNK.get());
                output.accept(CCBlocks.GREEN_SULPHUR_POOL.get());
                output.accept(CCBlocks.ORANGE_SULPHUR_POOL.get());
                output.accept(CCBlocks.RED_SULPHUR_POOL.get());
                output.accept(CCBlocks.YELLOW_SULPHUR_POOL.get());
                output.accept(CCBlocks.VERMILLION_SULPHUR_POOL.get());
                output.accept(CCBlocks.SULPHUR_WATER_VENT_BASE.get());
                output.accept(CCBlocks.SULPHUR_WATER_VENT_TOP.get());
                output.accept(CCBlocks.RED_SULPHUR_WATER_VENT_BASE.get());
                output.accept(CCBlocks.RED_SULPHUR_WATER_VENT_TOP.get());
                output.accept(CCBlocks.SULPHUR_DUST.get());
                output.accept(CCBlocks.SULPHUR_DUST_LAYER.get());
                output.accept(CCBlocks.SULPHURIC_SOIL.get());
                output.accept(CCBlocks.SULPHUR_CRYSTAL.get());
                output.accept(CCBlocks.SMALL_SULPHUR_CLUSTER.get());
                output.accept(CCBlocks.MEDIUM_SULPHUR_CLUSTER.get());
                output.accept(CCBlocks.TALL_SULPHUR_CLUSTER.get());
                output.accept(CCBlocks.VOLCANITE_BLOCK.get());
                output.accept(CCBlocks.THUNDERSTONE.get());
                output.accept(CCBlocks.THUNDERSTONE_STAIRS.get());
                output.accept(CCBlocks.THUNDERSTONE_SLAB.get());
                output.accept(CCBlocks.THUNDERSTONE_WALL.get());
                output.accept(CCBlocks.CHARGED_THUNDERSTONE.get());
                output.accept(CCBlocks.THUNDERSTONE_BRICKS.get());
                output.accept(CCBlocks.THUNDERSTONE_BRICKS_STAIRS.get());
                output.accept(CCBlocks.THUNDERSTONE_BRICKS_SLAB.get());
                output.accept(CCBlocks.THUNDERSTONE_BRICKS_WALL.get());
                output.accept(CCBlocks.CHISELED_THUNDERSTONE.get());
                output.accept(CCBlocks.CHISELED_THUNDERSTONE_STAIRS.get());
                output.accept(CCBlocks.CHISELED_THUNDERSTONE_SLAB.get());
                output.accept(CCBlocks.CHISELED_THUNDERSTONE_WALL.get());
                output.accept(CCBlocks.POLISHED_THUNDERSTONE.get());
                output.accept(CCBlocks.POLISHED_THUNDERSTONE_STAIRS.get());
                output.accept(CCBlocks.POLISHED_THUNDERSTONE_SLAB.get());
                output.accept(CCBlocks.POLISHED_THUNDERSTONE_WALL.get());

            }).build());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CC_TAB_ITEMS = CREATIVE_MODE_TABS.register("cc_tab_items", () -> CreativeModeTab.builder()
            .title(Component.translatable("itemGroup.items." + CrystalChronicles.MODID))
            .icon(() -> CCItems.DIVINITE_SHARD.get().getDefaultInstance())
            .displayItems((parameters, output) -> {
                output.accept(CCItems.HEMALITE_SHARD.get());
                output.accept(CCItems.VOIDSTONE_SHARD.get());
                output.accept(CCItems.DIVINITE_SHARD.get());
                output.accept(CCItems.VOLTITE_SHARD.get());
                output.accept(CCItems.FLORALITE_SHARD.get());
                output.accept(CCItems.VOLCANITE_SHARD.get());
                output.accept(CCItems.ICE_SHARD.get());
                output.accept(CCItems.FAT_TISSUE_BALL.get());
                output.accept(CCItems.NEURON.get());
                output.accept(CCItems.EYE.get());
                output.accept(CCFluids.BLOOD_BUCKET.get());
                output.accept(CCItems.CLOUD_BUCKET.get());
                output.accept(CCFluids.SULPHURIC_WATER_BUCKET.get());
            }).build());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CC_TAB_ARMORY = CREATIVE_MODE_TABS.register("cc_tab_armory", () -> CreativeModeTab.builder()
            .title(Component.translatable("itemGroup.armory." + CrystalChronicles.MODID))
            .icon(() -> CCItems.PRISMATIC_KNIGHT_HELMET.get().getDefaultInstance())
            .displayItems((parameters, output) -> {
                output.accept(CCItems.HOLY_KNIGHT_HELMET.get());
                output.accept(CCItems.HOLY_KNIGHT_CHESTPLATE.get());
                output.accept(CCItems.HOLY_KNIGHT_LEGGINGS.get());
                output.accept(CCItems.HOLY_KNIGHT_BOOTS.get());
                output.accept(CCItems.HOLY_SWORD.get());
                output.accept(CCItems.HOLY_SHIELD.get());
                output.accept(CCItems.ICE_KNIGHT_HELMET.get());
                output.accept(CCItems.ICE_KNIGHT_CHESTPLATE.get());
                output.accept(CCItems.ICE_KNIGHT_LEGGINGS.get());
                output.accept(CCItems.ICE_KNIGHT_BOOTS.get());
                output.accept(CCItems.ICE_HAMMER.get());
                output.accept(CCItems.ENDER_MAGE_HELMET.get());
                output.accept(CCItems.ENDER_MAGE_CHESTPLATE.get());
                output.accept(CCItems.ENDER_MAGE_LEGGINGS.get());
                output.accept(CCItems.ENDER_MAGE_BOOTS.get());
                output.accept(CCItems.ENDER_SICKLE.get());
                output.accept(CCItems.ENDER_STAFF.get());
                output.accept(CCItems.BLOOD_KNIGHT_HELMET.get());
                output.accept(CCItems.BLOOD_KNIGHT_CHESTPLATE.get());
                output.accept(CCItems.BLOOD_KNIGHT_LEGGINGS.get());
                output.accept(CCItems.BLOOD_KNIGHT_BOOTS.get());
                output.accept(CCItems.BLOOD_SCYTHE.get());
                output.accept(CCItems.FIRE_KNIGHT_HELMET.get());
                output.accept(CCItems.FIRE_KNIGHT_CHESTPLATE.get());
                output.accept(CCItems.FIRE_KNIGHT_LEGGINGS.get());
                output.accept(CCItems.FIRE_KNIGHT_BOOTS.get());
                output.accept(CCItems.FIRE_CHAKRAM.get());
                output.accept(CCItems.NATURE_KNIGHT_HELMET.get());
                output.accept(CCItems.NATURE_KNIGHT_CHESTPLATE.get());
                output.accept(CCItems.NATURE_KNIGHT_LEGGINGS.get());
                output.accept(CCItems.NATURE_KNIGHT_BOOTS.get());
                output.accept(CCItems.NATURE_SPEAR.get());
                output.accept(CCItems.LIGHTNING_KNIGHT_HELMET.get());
                output.accept(CCItems.LIGHTNING_KNIGHT_CHESTPLATE.get());
                output.accept(CCItems.LIGHTNING_KNIGHT_LEGGINGS.get());
                output.accept(CCItems.LIGHTNING_KNIGHT_BOOTS.get());
                output.accept(CCItems.LIGHTNING_BIDENT.get());
                output.accept(CCItems.LIGHTNING_STAFF.get());
                output.accept(CCItems.EVOCATION_KNIGHT_HELMET.get());
                output.accept(CCItems.EVOCATION_KNIGHT_CHESTPLATE.get());
                output.accept(CCItems.EVOCATION_KNIGHT_LEGGINGS.get());
                output.accept(CCItems.EVOCATION_KNIGHT_BOOTS.get());
                output.accept(CCItems.EVOCATION_TWINBLADE.get());

                output.accept(CCItems.PRISMATIC_KNIGHT_HELMET.get());
                output.accept(CCItems.PRISMATIC_KNIGHT_CHESTPLATE.get());
                output.accept(CCItems.PRISMATIC_KNIGHT_LEGGINGS.get());
                output.accept(CCItems.PRISMATIC_KNIGHT_BOOTS.get());
                output.accept(CCItems.DIFFRACTION_RING.get());
            }).build());

    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }

}
